# Generated by Django 3.0.3 on 2020-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_nine', '0003_auto_20200309_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='bad',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='review',
            name='good',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
