# Generated by Django 3.0.3 on 2020-03-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_nine', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
