# Generated by Django 3.0.3 on 2020-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_four', '0002_article_author_book_example_place_publication_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
    ]
