# Generated by Django 3.0.3 on 2020-02-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_four', '0003_auto_20200225_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('headline',)},
        ),
    ]
